"""initial schema

Revision ID: 8034a5c43e3f
Revises: 
Create Date: 2026-02-21 01:02:59.615468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8034a5c43e3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('engine_cc', sa.Integer(), nullable=False),
    sa.Column('bhp', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_uk_survivors', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('price_gbp', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('colour', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('source_site', sa.String(length=60), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_sold', sa.Boolean(), nullable=True),
    sa.Column('listed_at', sa.Date(), nullable=True),
    sa.Column('sold_at', sa.Date(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['model_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('price_gbp', sa.Integer(), nullable=False),
    sa.Column('year_of_car', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=True),
    sa.Column('sold_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['model_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registry_cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('colour', sa.String(length=40), nullable=True),
    sa.Column('chassis_prefix', sa.String(length=20), nullable=True),
    sa.Column('location_region', sa.String(length=60), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('mot_status', sa.String(length=20), nullable=True),
    sa.Column('mot_expiry', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['model_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registry_cars')
    op.drop_table('price_records')
    op.drop_table('listings')
    op.drop_table('model_variants')
    # ### end Alembic commands ###
